version: "3.4"

services:
  api:
    build: ./RestMongoDocker
    restart: always
    ports:
      - 5000:80
      - 5001:443
    environment:
      MongoDB__Host: mongo
    depends_on:
      - mongo

  consumer:
    build: ./LoyaltyService.Consumer
    restart: always
    depends_on:
      - api